### ISSUE TITLE
carousel not working

### ISSUE THREAD

**Issue by pcvenk** [masoomulhaqs/mk-3Dcarousel#1]
I copied the stated example followed the specified instructions but I am not able to get it working. No idea why... 

html: `<div class="mk-carousel" id="mkCarousel">
      <img class="active" src="https://unsplash.it/500/500?image=893" alt="">
      <img src="https://unsplash.it/500/500?image=693" alt="">
      <img src="https://unsplash.it/500/500?image=593" alt="">
      <img src="https://unsplash.it/500/500?image=493" alt="">
      <img src="https://unsplash.it/500/500?image=393" alt="">
      <img src="https://unsplash.it/500/500?image=293" alt="">
      <img src="https://unsplash.it/500/500?image=193" alt="">
    </div>`

just before the closing body tag i inserted these scripts:
`<script src="/bower_components/jquery/dist/jquery.js"></script>
 <script src="scripts/mk-3Dcarousel.js"></script>`

js: `$(function(){
    $('#mkCarousel').mkCarousel();
  });`

Any idea?

**Comment by masoomulhaqs** [comment]
Did you link `mk-3Dcarousel.css` file to your webpage @pcvenk ?

I hope your find it as issue, because you didn't link the css file. Please link and check, and also leave a comment about the status.
